FROM alpine:3.10

ENV APP_HOME /app
#RUN mkdir $APP_HOME - should be installed by Docker during next step COPY Gemfile*
COPY Gemfile* $APP_HOME/
WORKDIR $APP_HOME

RUN apk --no-cache update \
    && apk add --no-cache ruby-full ruby-dev build-base \
    && gem install bundler:1.17.2 --no-ri --no-rdoc \
    # && gem install bundler --no-ri --no-rdoc \ - threw error:Could not find 'bundler' (1.17.2) required by your /app/Gemfile.lock
    && bundle install \
    && apk del ruby-dev build-base

#RUN bundle install
COPY . $APP_HOME

ENV POST_SERVICE_HOST post
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment
ENV COMMENT_SERVICE_PORT 9292

CMD ["puma"]
