global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#ivan_boriskin'

