FROM alpine:3.10

ENV APP_HOME /app
# RUN mkdir $APP_HOME
COPY Gemfile* $APP_HOME/
WORKDIR $APP_HOME

RUN apk --no-cache update \
    && apk add ruby-full build-base ruby-dev \
    && gem install bundler:1.17.2 --no-ri --no-rdoc \
    && bundle install \
    && apk del build-base ruby-dev 

#RUN bundle install
COPY . $APP_HOME

ENV COMMENT_DATABASE_HOST comment_db
ENV COMMENT_DATABASE comments

CMD ["puma"]
