---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "comment.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "comment.fullname" . }}
          servicePort: {{ .Values.service.externalPort }}
...
