---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ui.fullname" . }}         # unique name of running resource
  labels:
    app: reddit
    component: ui
    release: {{ .Release.Name }}                      # mark the release
spec:
  type: NodePort
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}    # pick the PODs only this release
  selector:
    app: reddit
    component: ui
    release: {{ .Release.Name }}
...

