version: '3.5'
services:

  post_db:
    hostname: post_db
    container_name: post_db
    image: mongo:${MONGODB_VER}
#    env_file: .env
    volumes:
      - post_db:/data/db
    networks:
      backend_net:
        aliases:
          - post_db
          - comment_db

  ui:
    hostname: ui
    container_name: ui
#    build: ./ui
#    env_file: .env
    image: ${USER_NAME}/ui:${UI_VER}
    environment:
      - POST_SERVICE_HOST=post
      - POST_SERVICE_PORT=5000
      - COMMENT_SERVICE_HOST=comment
      - COMMENT_SERVICE_PORT=9292
    ports:
      - ${UI_HOST_PORT}:${UI_CNTR_PORT}/tcp
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    networks:
      - ${NETW_BACK}

  post:
    hostname: post
#    build: ./post-py
    container_name: post
#    env_file: .env
    image: ${USER_NAME}/post:${POST_VER}
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    networks:
      - ${NETW_FRONT}
      - ${NETW_BACK}

  comment:
    hostname: comment
#    build: ./comment
    container_name: comment
#    env_file: .env
    image: ${USER_NAME}/comment:${COMMENT_VER}
    networks:
      - ${NETW_FRONT}
      - ${NETW_BACK}

volumes:
  post_db:

networks:
  frontend_net:
    name: ${NETW_FRONT}
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: ${SUBNET_FRONT}

  backend_net:
    name: ${NETW_BACK}
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: ${SUBNET_BACK}
