version: '3.5'
services:

  zipkin:
    image: openzipkin/zipkin
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - "9411:9411"
    networks:
      - ${NETW_FRONT}
      - ${NETW_BACK}

  fluentd:
    image: ${USER_NAME}/fluentd
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:6.8.3
    expose:
      - 9200
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - "9200:9200"

  kibana:
    image: kibana:6.8.3
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - "5601:5601"
    depends_on: ['elasticsearch']


networks:
  frontend_net:
    name: ${NETW_FRONT}
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: ${SUBNET_FRONT}

  backend_net:
    name: ${NETW_BACK}
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: ${SUBNET_BACK}
