version: '3.5'
services:
  post_db:
    hostname: post_db
    image: mongo:${MONGODB_VER}
#    env_file: .env
    volumes:
      - post_db:/data/db
    networks:
      backend_net:
        aliases:
          - post_db
          - comment_db

  ui:
    hostname: ui
#    build: ./ui
    image: ${USERNAME}/ui:${UI_VER}
    ports:
      - ${UI_HOST_PORT}:${UI_CNTR_PORT}/tcp
    networks:
      - ${NETW_BACK}

  post:
    hostname: post
#    build: ./post-py
    image: ${USERNAME}/post:${POST_VER}
    networks:
      - ${NETW_FRONT}
      - ${NETW_BACK}

  comment:
    hostname: comment
#    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VER}
    networks:
      - ${NETW_FRONT}
      - ${NETW_BACK}
#      - reddit_front
#      - reddit_back

  prometheus:
    hostname: prometheus
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - ${NETW_FRONT}
      - ${NETW_BACK}
#      - reddit_front
#      - reddit_back


volumes:
  post_db:
  prometheus_data:

networks:
  frontend_net:
    name: ${NETW_FRONT}
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: ${SUBNET_FRONT}

  backend_net:
    name: ${NETW_BACK}
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: ${SUBNET_BACK}
