---
global:
  scrape_interval: '5s'
  evaluation_interval: 5s

rule_files:
  - "alerts.yml"


alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets:
        - 'node-exporter:9100'

  - job_name: 'docker-host'
    static_configs:
      - targets: ['104.155.30.194:9323']
        labels:
          group: 'docker-host'

  - job_name: 'mongodb_exporter'
    static_configs:
      - targets: ['mongodb_exporter:9216']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://ui:9292    
        - http://post:5000   
        - http://comment:9292 
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115  # The blackbox exporter's real hostname:port.

# Collect metric from post service
  - job_name: 'post'
    static_configs:
      - targets:
        - 'post:5000'

  - job_name: 'cadvisor'
    static_configs:
      - targets:
        - 'cadvisor:8080'


  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'localhost:9090'

  - job_name: 'telegraf'
    static_configs:
      - targets: 
        - 'telegraf:9273'

  - job_name: 'ui'
    static_configs:
      - targets:
        - 'ui:9292'

  - job_name: 'comment'
    static_configs:
      - targets:
        - 'comment:9292'
