kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: FTgNWWlxLZ8mu/rIX7tQjUDVf1Bvy8GqpcQGIzegX1A=
      - identity: {}
