version: '3.7'
services:
  post:
    volumes:
      - ./post-py:/app
  comment:
    volumes:
      - ./comment:/app
    command: ["puma", "--debug", "-w", "2"]
  ui:
    volumes:
      - ./ui:/app
    command: ["puma", "--debug", "-w", "2"]
